source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'VIPER-ListSimpsonQuotes' do
    pod 'Alamofire'
    pod 'PKHUD', '~> 5.0'
    pod 'Kingfisher', '~> 5.0'
    pod 'AlamofireObjectMapper'
    pod 'ObjectMapper'
end
