# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'VIPER-ListSimpsonQuotes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    # Pods for VIPER-ListSimpsonQuotes
   pod 'PKHUD', '~> 5.0'


end
